### PR TITLE
Fixed build process to now successfully compile on (some) modern *nixes.

### PR DESCRIPTION
**Pull request by suetanvil**
Unfortunately, Ularn will not work as a 64-bit application, so I
modified configure.ac to force it to be built as a 32-bit one.  This
has been tested on Ubuntu 18LTS, macOS with MacPorts and Raspbian.

Also:

 -Moved the save file to a (world-writable) subdir
 -Moved libs to the end of the link command
 -Added a pre-generated 'configure' and 'config.h.in'
 -Updated INSTALL instructions (old one is renamed for posterity).

### CODE REVIEW

**Comment by joshbressers** [comment]
I'm unsure this is needed. I have Ularn working quite well on Fedora x86_64. I'll investigate Ubuntu to see if there is something different there.

**Comment by suetanvil** [comment]
Much to my annoyance, I just tried rebuilding the master branch on Ubuntu 16LTS (the only Ubuntu machine I had handy) and after fixing a link error, the resulting 64-bit executable seems to be working fine.

The link error is due to the libs being first in the linker command line. They're in LDFLAGS when they should be in (I think) SYS_LIBRARIES.

So there's definitely something wierd going on here.

Also, it definitely doesn't build under macOS. That's due to Clang being less tolerant of some of the pre-ANSI quirks, but can be fixed with compiler options.

**Comment by joshbressers** [comment]
The code is super janky. I found a few errors with LTS 18, I'll try to fix this up and figure it out. I did get it mostly working though.

**Comment by joshbressers** [comment]
I just pushed a commit that should fix the build for you. I verified it works on Ubuntu 18 and OSX. There's still some work to be done around cleaning up this horrible old code, but this is enough to get it running again.

**Pull request closed without merging**
